import os
import re
import logging
from datetime import datetime, timezone

logger = logging.getLogger("planner.py_gen")

_FILE_HEADER = '''"""
Generated by Planner Service
App: {app_id}
Generated: {timestamp}
DO NOT EDIT — regenerate via POST /plan/run
"""

import pytest
from playwright.async_api import Page

from src.utils.json_data_provider import JsonDataProvider
from src.utils.selector_registry import SelectorRegistry
{page_imports}

SelectorRegistry.load()

'''

_IMPORTS_MARKER = "from src.pages.generated"


def _method_to_snake(name: str) -> str:
    s1 = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def _tc_name_to_method(tc_name: str) -> str:
    cleaned = re.sub(r'[^a-zA-Z0-9\s]', ' ', tc_name)
    words = [w.lower() for w in cleaned.split() if w]
    if not words:
        return "test_case"
    return "_".join(words)


def _class_to_module(class_name: str) -> str:
    s1 = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', class_name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def _existing_method_names(file_path: str) -> set:
    if not os.path.exists(file_path):
        return set()
    names: set = set()
    with open(file_path) as f:
        for line in f:
            m = re.match(r'^async def (test_\w+)\(', line.strip())
            if m:
                names.add(m.group(1))
    return names


def _build_test_function(planner_output: dict, description: str, method_name: str) -> str:
    params = planner_output.get("parameters", [])
    steps = planner_output.get("steps", [])
    starting_class = planner_output.get("startingClass", "")
    final_assertion = planner_output.get("finalAssertion") or {}
    confidence = planner_output.get("confidence", 0)

    data_file = method_name  # snake_case method name maps to snake_case json file

    low_conf = ""
    if confidence < 0.75:
        low_conf = f"    # WARNING: Low confidence ({confidence:.2f}) — verify this sequence manually\n"

    steps = [s for s in steps if s.get("methodName", "").lower() != "launch"]
    chain_lines = [f"    p = {starting_class}(page)"]
    for step in steps:
        mname = _method_to_snake(step.get("methodName", ""))
        if step.get("hasParameter") and step.get("parameterName"):
            chain_lines.append(f"    await p.{mname}(data['{step['parameterName']}'])")
        else:
            chain_lines.append(f"    await p.{mname}()")

    if final_assertion.get("methodName"):
        a_mname = _method_to_snake(final_assertion["methodName"])
        a_param = final_assertion.get("parameterName", "")
        if a_param:
            chain_lines.append(f"    await p.{a_mname}(data['{a_param}'])")
        else:
            chain_lines.append(f"    await p.{a_mname}()")
    else:
        chain_lines.append("    await p.assert_page_loaded()")

    chain = "\n".join(chain_lines)

    return (
        f"_cases_{method_name} = JsonDataProvider.get_data('{data_file}')\n"
        f"\n"
        f"\n"
        f"@pytest.mark.parametrize('data', _cases_{method_name})\n"
        f"async def {method_name}(page: Page, data: dict) -> None:\n"
        f"{low_conf}"
        f"{chain}\n"
    )


def generate(planner_output: dict, app_id: str, framework_dir: str,
             description: str = "", tc_name: str = "") -> tuple[str, str]:
    starting_class = planner_output.get("startingClass", "Generated")
    module_name = _class_to_module(starting_class.replace("Page", ""))
    file_stem = f"test_{module_name}"

    tests_dir = os.path.join(framework_dir, "tests", "generated")
    os.makedirs(tests_dir, exist_ok=True)
    # ensure __init__.py exists
    init_path = os.path.join(tests_dir, "__init__.py")
    if not os.path.exists(init_path):
        open(init_path, "w").close()

    file_path = os.path.join(tests_dir, f"{file_stem}.py")

    base_name = _tc_name_to_method(tc_name) if tc_name else planner_output.get("testMethodName", "test_case")
    # ensure test_ prefix
    if not base_name.startswith("test_"):
        base_name = "test_" + base_name

    existing = _existing_method_names(file_path)
    method_name = base_name
    if base_name in existing:
        i = 2
        while f"{base_name}_{i}" in existing:
            i += 1
        method_name = f"{base_name}_{i}"

    class_module = _class_to_module(starting_class)
    page_import = f"from src.pages.generated.{class_module} import {starting_class}"
    new_block = _build_test_function(planner_output, description, method_name)

    if os.path.exists(file_path):
        with open(file_path) as f:
            content = f.read()
        content = content.rstrip() + "\n\n\n" + new_block
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Appended test to {file_stem}.py")
    else:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        header = _FILE_HEADER.format(app_id=app_id, timestamp=ts, page_imports=page_import)
        content = header + new_block
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Created {file_stem}.py")

    return file_path, method_name
