import os
import re
import logging
from datetime import datetime, timezone

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

logger = logging.getLogger("planner.test_gen")

FILE_HEADER = """package tests.generated;

import org.testng.annotations.*;
import pages.*;
import base.BasePage;
import utils.JsonDataProvider;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import io.github.bonigarcia.wdm.WebDriverManager;
import java.lang.reflect.Method;

/**
 * Generated by Planner Service
 * App: {app_id}
 * Generated: {timestamp}
 * DO NOT EDIT — regenerate via POST /plan/run
 */
public class {class_name} {{

    private WebDriver driver;

    @BeforeMethod
    public void setUp() {{
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get(System.getProperty("app.url", ""));
    }}

    @AfterMethod
    public void tearDown() {{
        if (driver != null) driver.quit();
    }}

"""

SETUP_MARKER = "@BeforeMethod"
DATA_PROVIDER_MARKER = "@DataProvider(name = \"jsonData\")"


def _tc_name_to_method(tc_name: str) -> str:
    """Convert a user-provided test case name to a valid Java camelCase method identifier."""
    cleaned = re.sub(r'[^a-zA-Z0-9\s]', ' ', tc_name)
    words = [w for w in cleaned.split() if w]
    if not words:
        return "testCase"
    method = words[0].lower() + "".join(w.title() for w in words[1:])
    if method[0].isdigit():
        method = "tc" + method
    return method


def _existing_method_names(file_path: str) -> set:
    """Return all non-lifecycle method names already in the Java file."""
    if not os.path.exists(file_path):
        return set()
    names: set = set()
    with open(file_path) as f:
        for line in f:
            m = re.search(r'public void (\w+)\(', line)
            if m and m.group(1) not in ("setUp", "tearDown"):
                names.add(m.group(1))
    return names


def _llm_rename(tc_name: str, description: str, existing: set) -> str:
    """Ask LLM for a unique Java method name when the derived one collides."""
    try:
        model = ChatOpenAI(
            model="gpt-4o-mini",
            api_key=os.environ.get("OPENAI_API_KEY", ""),
            max_tokens=30,
        )
        prompt = (
            f"Generate a unique Java camelCase method name for this test case.\n"
            f"Test case name: {tc_name}\n"
            f"Description: {description}\n"
            f"Already taken: {', '.join(sorted(existing))}\n"
            f"Return ONLY the method name, nothing else."
        )
        resp = model.invoke([HumanMessage(content=prompt)])
        raw = str(resp.content).strip()
        name = re.sub(r'[^a-zA-Z0-9_]', '', raw.split()[0] if raw.split() else "")
        if name and name[0].isdigit():
            name = "tc" + name
        return name or "testCase"
    except Exception as e:
        logger.warning(f"LLM rename failed: {e} — falling back to counter")
        base = _tc_name_to_method(tc_name)
        i = 2
        while f"{base}{i}" in existing:
            i += 1
        return f"{base}{i}"


def _build_method(planner_output: dict, description: str, method_name: str) -> str:
    confidence = planner_output.get("confidence", 0)
    params = planner_output.get("parameters", [])
    steps = planner_output.get("steps", [])
    starting_class = planner_output.get("startingClass", "")
    final_assertion = planner_output.get("finalAssertion") or {}

    param_decl = ", ".join(f"{p['type']} {p['name']}" for p in params)

    low_conf_comment = ""
    if confidence < 0.75:
        low_conf_comment = f"    // WARNING: Low confidence ({confidence:.2f}) — verify this sequence manually\n"

    steps = [s for s in steps if s.get("methodName", "").lower() != "launch"]
    chain_parts = []
    for step in steps:
        mname = step.get("methodName", "")
        if step.get("hasParameter") and step.get("parameterName"):
            chain_parts.append(f".{mname}({step['parameterName']})")
        else:
            chain_parts.append(f".{mname}()")

    if final_assertion.get("methodName"):
        a_param = final_assertion.get("parameterName", "")
        chain_parts.append(f".{final_assertion['methodName']}({a_param})")
    else:
        # Default assertion: use expectedResult param if declared, else assertPageLoaded()
        result_param = next((p["name"] for p in params if "expected" in p["name"].lower()), None)
        if result_param:
            chain_parts.append(f".assertResult({result_param})")
        else:
            chain_parts.append(".assertPageLoaded()")

    indent = "            "
    chain = f"\n{indent}".join(chain_parts)

    return (
        f"\n"
        f"    @Test(dataProvider = \"jsonData\", dataProviderClass = JsonDataProvider.class,\n"
        f"          description = \"{description}\")\n"
        f"{low_conf_comment}"
        f"    public void {method_name}({param_decl}) {{\n"
        f"        new {starting_class}(driver)\n"
        f"            {chain};\n"
        f"    }}\n"
    )


def generate(planner_output: dict, app_id: str, java_dir: str, description: str = "", tc_name: str = "") -> tuple[str, str]:
    starting_class = planner_output.get("startingClass", "Generated")
    class_name = starting_class.replace("Page", "") + "Tests" if starting_class else "GeneratedTests"

    tests_dir = os.path.join(java_dir, "src", "test", "java", "tests", "generated")
    os.makedirs(tests_dir, exist_ok=True)
    file_path = os.path.join(tests_dir, f"{class_name}.java")

    base_name = _tc_name_to_method(tc_name) if tc_name else planner_output.get("testMethodName", "testCase")
    existing = _existing_method_names(file_path)
    if base_name in existing:
        method_name = _llm_rename(tc_name or base_name, description, existing)
    else:
        method_name = base_name

    new_method = _build_method(planner_output, description, method_name)

    if os.path.exists(file_path):
        with open(file_path) as f:
            content = f.read()
        content = content.rstrip().rstrip("}") + new_method + "}\n"
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Appended test method to {class_name}.java")
    else:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        header = FILE_HEADER.format(app_id=app_id, timestamp=ts, class_name=class_name)
        content = header + new_method + "}\n"
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Created {class_name}.java")

    return file_path, method_name
