import os
import logging
from datetime import datetime, timezone

logger = logging.getLogger("planner.test_gen")

FILE_HEADER = """package tests.generated;

import org.testng.annotations.*;
import pages.*;
import base.BasePage;
import utils.ExcelReader;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import io.github.bonigarcia.wdm.WebDriverManager;
import java.lang.reflect.Method;

/**
 * Generated by Planner Service
 * App: {app_id}
 * Generated: {timestamp}
 * DO NOT EDIT — regenerate via POST /plan/run
 */
public class {class_name} {{

    private WebDriver driver;

    @BeforeMethod
    public void setUp() {{
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get(System.getProperty("app.url", ""));
    }}

    @AfterMethod
    public void tearDown() {{
        if (driver != null) driver.quit();
    }}

    @DataProvider(name = "excelData")
    public static Object[][] getData(Method m) {{
        return ExcelReader.getRowsByHeader(m.getName());
    }}
"""

SETUP_MARKER = "@BeforeMethod"
DATA_PROVIDER_MARKER = "@DataProvider(name = \"excelData\")"


def _build_method(planner_output: dict, description: str) -> str:
    method_name = planner_output.get("testMethodName", "TC_Unknown")
    confidence = planner_output.get("confidence", 0)
    params = planner_output.get("parameters", [])
    steps = planner_output.get("steps", [])
    starting_class = planner_output.get("startingClass", "")
    final_assertion = planner_output.get("finalAssertion", {})

    param_decl = ", ".join(f"{p['type']} {p['name']}" for p in params)

    low_conf_comment = ""
    if confidence < 0.75:
        low_conf_comment = f"    // WARNING: Low confidence ({confidence:.2f}) — verify this sequence manually\n"

    steps = [s for s in steps if s.get("methodName", "").lower() != "launch"]
    chain_parts = []
    for step in steps:
        mname = step.get("methodName", "")
        if step.get("hasParameter") and step.get("parameterName"):
            chain_parts.append(f".{mname}({step['parameterName']})")
        else:
            chain_parts.append(f".{mname}()")

    if final_assertion.get("methodName"):
        a_param = final_assertion.get("parameterName", "")
        chain_parts.append(f".{final_assertion['methodName']}({a_param})")

    indent = "            "
    chain = f"\n{indent}".join(chain_parts)

    return (
        f"\n"
        f"    @Test(dataProvider = \"excelData\",\n"
        f"          description = \"{description}\")\n"
        f"{low_conf_comment}"
        f"    public void {method_name}({param_decl}) {{\n"
        f"        new {starting_class}(driver)\n"
        f"            {chain};\n"
        f"    }}\n"
    )


def generate(planner_output: dict, app_id: str, java_dir: str, description: str = "") -> str:
    starting_class = planner_output.get("startingClass", "Generated")
    class_name = starting_class.replace("Page", "") + "Tests" if starting_class else "GeneratedTests"

    tests_dir = os.path.join(java_dir, "src", "test", "java", "tests", "generated")
    os.makedirs(tests_dir, exist_ok=True)
    file_path = os.path.join(tests_dir, f"{class_name}.java")

    new_method = _build_method(planner_output, description)

    if os.path.exists(file_path):
        with open(file_path) as f:
            content = f.read()
        content = content.rstrip().rstrip("}") + new_method + "}\n"
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Appended test method to {class_name}.java")
    else:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        header = FILE_HEADER.format(app_id=app_id, timestamp=ts, class_name=class_name)
        content = header + new_method + "}\n"
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Created {class_name}.java")

    return file_path
