import os
import re
import logging
from datetime import datetime, timezone

logger = logging.getLogger("planner.ts_gen")

_FILE_HEADER = """/**
 * Generated by Planner Service
 * App: {app_id}
 * Generated: {timestamp}
 * DO NOT EDIT — regenerate via POST /plan/run
 */

import {{ chromium, Browser, Page }} from 'playwright';
import {{ JsonDataProvider }} from '../../src/utils/JsonDataProvider';
import {{ SelectorRegistry }} from '../../src/utils/SelectorRegistry';
{page_imports}

SelectorRegistry.load();

let browser: Browser;
let page: Page;

beforeAll(async () => {{
  browser = await chromium.launch({{ headless: true }});
}});

afterAll(async () => {{
  await browser.close();
}});

beforeEach(async () => {{
  const context = await browser.newContext();
  page = await context.newPage();
  await page.goto(process.env.APP_URL ?? '');
}});

afterEach(async () => {{
  await page.context().close();
}});

describe('{class_name}', () => {{
"""

_FILE_FOOTER = "});\n"


def _tc_name_to_method(tc_name: str) -> str:
    cleaned = re.sub(r'[^a-zA-Z0-9\s]', ' ', tc_name)
    words = [w for w in cleaned.split() if w]
    if not words:
        return "testCase"
    method = words[0].lower() + "".join(w.title() for w in words[1:])
    if method[0].isdigit():
        method = "tc" + method
    return method


def _existing_method_names(file_path: str) -> set:
    if not os.path.exists(file_path):
        return set()
    names: set = set()
    with open(file_path) as f:
        for line in f:
            m = re.search(r"test\.each\(.*?\)\(\s*'(\w+)", line)
            if m:
                names.add(m.group(1))
    return names


def _build_type_annotation(params: list) -> str:
    if not params:
        return "Record<string, string>"
    fields = "; ".join(f"{p['name']}: string" for p in params)
    return "{ " + fields + " }"


def _build_step_chain(steps: list, starting_class: str, final_assertion: dict) -> list[str]:
    """Build step lines, tracking page object variable per navigation step."""
    lines = [f"    let p: any = new {starting_class}(page);"]
    for step in steps:
        mname = step.get("methodName", "")
        is_nav = step.get("isNavigation", False)
        if step.get("hasParameter") and step.get("parameterName"):
            call = f"p.{mname}(data.{step['parameterName']})"
        else:
            call = f"p.{mname}()"
        if is_nav:
            lines.append(f"    p = await {call};")
        else:
            lines.append(f"    await {call};")

    if final_assertion.get("methodName"):
        a_param = final_assertion.get("parameterName", "")
        if a_param:
            lines.append(f"    await p.{final_assertion['methodName']}(data.{a_param});")
        else:
            lines.append(f"    await p.{final_assertion['methodName']}();")
    else:
        lines.append("    await p.assertPageLoaded();")
    return lines


def _build_test_block(planner_output: dict, description: str, method_name: str) -> str:
    params = planner_output.get("parameters", [])
    steps = planner_output.get("steps", [])
    starting_class = planner_output.get("startingClass", "")
    final_assertion = planner_output.get("finalAssertion") or {}
    confidence = planner_output.get("confidence", 0)
    type_ann = _build_type_annotation(params)

    low_conf = ""
    if confidence < 0.75:
        low_conf = f"    // WARNING: Low confidence ({confidence:.2f}) — verify this sequence manually\n"

    steps = [s for s in steps if s.get("methodName", "").lower() != "launch"]
    chain_lines = _build_step_chain(steps, starting_class, final_assertion)
    chain = "\n".join(chain_lines)

    return (
        f"\n"
        f"  type CaseRow_{method_name} = {type_ann};\n"
        f"  const cases_{method_name} = JsonDataProvider.getData<CaseRow_{method_name}>('{method_name}');\n"
        f"  test.each(cases_{method_name}.map((d, i) => [i, d] as [number, CaseRow_{method_name}]))(\n"
        f"    '{method_name} [%i]',\n"
        f"    async (_i: number, data: CaseRow_{method_name}) => {{\n"
        f"{low_conf}"
        f"{chain}\n"
        f"    }}\n"
        f"  );\n"
    )


def generate(planner_output: dict, app_id: str, framework_dir: str,
             description: str = "", tc_name: str = "") -> tuple[str, str]:
    starting_class = planner_output.get("startingClass", "Generated")
    class_name = (starting_class.replace("Page", "") + "Tests") if starting_class else "GeneratedTests"

    tests_dir = os.path.join(framework_dir, "tests", "generated")
    os.makedirs(tests_dir, exist_ok=True)
    file_path = os.path.join(tests_dir, f"{class_name}.test.ts")

    base_name = _tc_name_to_method(tc_name) if tc_name else planner_output.get("testMethodName", "testCase")
    existing = _existing_method_names(file_path)
    method_name = base_name
    if base_name in existing:
        i = 2
        while f"{base_name}{i}" in existing:
            i += 1
        method_name = f"{base_name}{i}"

    new_block = _build_test_block(planner_output, description, method_name)
    page_import = f"import {{ {starting_class} }} from '../../src/pages/{starting_class}';"

    if os.path.exists(file_path):
        with open(file_path) as f:
            content = f.read()
        # Strip closing `});` of the describe block, append new test, re-close
        idx = content.rfind("});")
        content = content[:idx].rstrip() + "\n" + new_block + _FILE_FOOTER
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Appended test to {class_name}.test.ts")
    else:
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        header = _FILE_HEADER.format(
            app_id=app_id, timestamp=ts, class_name=class_name, page_imports=page_import
        )
        content = header + new_block + _FILE_FOOTER
        with open(file_path, "w") as f:
            f.write(content)
        logger.info(f"Created {class_name}.test.ts")

    return file_path, method_name
